apiVersion: kubernetes.crossplane.io/v1alpha2
kind: Object
metadata:
  name: test-pod-crossplane
spec:
  providerConfigRef:
    name: default
  forProvider:
    manifest:
      apiVersion: v1
      kind: Pod
      metadata:
        name: mon-pod-nginx
        namespace: default
      spec:
        containers:
        - name: nginx
          image: nginx:latest
          ports:
          - containerPort: 80
